name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B -V -ntp -Dstyle.color=always package
      env:
        MAVEN_OPTS: -Djansi.force=true
