name: CI
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        java: ["11", "17"]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: "${{ matrix.java }}"
    - name: Build with Maven
      run: mvn -B -V -ntp -Dstyle.color=always package javadoc:javadoc
      env:
        MAVEN_OPTS: -Djansi.force=true
